
public class HospitalManagement extends javax.swing.JFrame {

    
    public HospitalManagement() {
        initComponents();
        this.setSize(762,488);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AddPatientMenu = new javax.swing.JMenuItem();
        SearchPatientMenu = new javax.swing.JMenuItem();
        DispslayPatientMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AddDoctorMenu = new javax.swing.JMenuItem();
        SearchDoctorMenu = new javax.swing.JMenuItem();
        DisplayDoctorsMenu = new javax.swing.JMenuItem();
        AnalysisMenu = new javax.swing.JMenu();
        AnalysisMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jMenu1.setText("Patients");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        AddPatientMenu.setText("Add Patient");
        AddPatientMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPatientMenuActionPerformed(evt);
            }
        });
        jMenu1.add(AddPatientMenu);

        SearchPatientMenu.setText("SearchPatient");
        SearchPatientMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPatientMenuActionPerformed(evt);
            }
        });
        jMenu1.add(SearchPatientMenu);

        DispslayPatientMenu.setText("Display Patients");
        DispslayPatientMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DispslayPatientMenuActionPerformed(evt);
            }
        });
        jMenu1.add(DispslayPatientMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Doctors");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        AddDoctorMenu.setText("Add Doctor");
        AddDoctorMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDoctorMenuActionPerformed(evt);
            }
        });
        jMenu2.add(AddDoctorMenu);

        SearchDoctorMenu.setText("Search Doctor");
        SearchDoctorMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchDoctorMenuActionPerformed(evt);
            }
        });
        jMenu2.add(SearchDoctorMenu);

        DisplayDoctorsMenu.setText("Display Doctors");
        DisplayDoctorsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayDoctorsMenuActionPerformed(evt);
            }
        });
        jMenu2.add(DisplayDoctorsMenu);

        jMenuBar1.add(jMenu2);

        AnalysisMenu.setText("Analysis");
        AnalysisMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalysisMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(AnalysisMenu);

        AnalysisMenu1.setText("Logout");
        AnalysisMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalysisMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(AnalysisMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void AddPatientMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPatientMenuActionPerformed
        this.setVisible(false);
        AddPatientFrame addPatient = new AddPatientFrame();
        addPatient.setVisible(true);
        addPatient.setLocationRelativeTo(null);// GUI comes in center
        addPatient.setTitle("Add Patient");
        addPatient.setSize(762,500);
    }//GEN-LAST:event_AddPatientMenuActionPerformed

    private void SearchPatientMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPatientMenuActionPerformed
        this.setVisible(false);
        SearchPatientFrame searchPatient = new SearchPatientFrame();
        searchPatient.setVisible(true);
        searchPatient.setLocationRelativeTo(null);// GUI comes in center
        searchPatient.setTitle("Search Patient");
        searchPatient.setSize(762,500);
    }//GEN-LAST:event_SearchPatientMenuActionPerformed

    private void DispslayPatientMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DispslayPatientMenuActionPerformed
        this.setVisible(false);
        DisplayPatientsFrame displayPatient = new DisplayPatientsFrame();
        displayPatient.setVisible(true);
        displayPatient.setLocationRelativeTo(null);// GUI comes in center
        displayPatient.setTitle("Patients");
        displayPatient.setSize(762,500);
    }//GEN-LAST:event_DispslayPatientMenuActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void AddDoctorMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDoctorMenuActionPerformed
        this.setVisible(false);
        AddDoctorFrame addDoctor = new AddDoctorFrame();
        addDoctor.setVisible(true);
        addDoctor.setLocationRelativeTo(null);// GUI comes in center
        addDoctor.setTitle("Add Doctor");
        addDoctor.setSize(762,500);
    }//GEN-LAST:event_AddDoctorMenuActionPerformed

    private void SearchDoctorMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchDoctorMenuActionPerformed
        this.setVisible(false);
        SearchDoctorFrame searchDoctor = new SearchDoctorFrame();
        searchDoctor.setVisible(true);
        searchDoctor.setLocationRelativeTo(null);// GUI comes in center
        searchDoctor.setTitle("Search Doctor");
        searchDoctor.setSize(762,500);
    }//GEN-LAST:event_SearchDoctorMenuActionPerformed

    private void DisplayDoctorsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayDoctorsMenuActionPerformed
        this.setVisible(false);
        DisplayDoctorsFrame displayDoctors = new DisplayDoctorsFrame();
        displayDoctors.setVisible(true);
        displayDoctors.setLocationRelativeTo(null);// GUI comes in center
        displayDoctors.setTitle("Doctors");
        displayDoctors.setSize(762,500);
    }//GEN-LAST:event_DisplayDoctorsMenuActionPerformed

    private void AnalysisMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalysisMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnalysisMenuActionPerformed

    private void AnalysisMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalysisMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnalysisMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalManagement().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddDoctorMenu;
    private javax.swing.JMenuItem AddPatientMenu;
    private javax.swing.JMenu AnalysisMenu;
    private javax.swing.JMenu AnalysisMenu1;
    private javax.swing.JMenuItem DisplayDoctorsMenu;
    private javax.swing.JMenuItem DispslayPatientMenu;
    private javax.swing.JMenuItem SearchDoctorMenu;
    private javax.swing.JMenuItem SearchPatientMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
