package modules;
public class PostLoginHomePage extends javax.swing.JFrame {

    
    public PostLoginHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        navPatient = new javax.swing.JButton();
        navDoctors = new javax.swing.JButton();
        navDepartments = new javax.swing.JButton();
        navAnalysis = new javax.swing.JButton();
        navLogout = new javax.swing.JButton();
        ContentPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(0, 0, 0));

        navbar.setBackground(new java.awt.Color(51, 51, 51));

        navPatient.setBackground(new java.awt.Color(51, 51, 51));
        navPatient.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        navPatient.setForeground(new java.awt.Color(0, 255, 255));
        navPatient.setText("Patients");
        navPatient.setBorder(null);
        navPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navPatientActionPerformed(evt);
            }
        });

        navDoctors.setBackground(new java.awt.Color(51, 51, 51));
        navDoctors.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        navDoctors.setForeground(new java.awt.Color(0, 255, 255));
        navDoctors.setText("Doctors");
        navDoctors.setBorder(null);
        navDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navDoctorsActionPerformed(evt);
            }
        });

        navDepartments.setBackground(new java.awt.Color(51, 51, 51));
        navDepartments.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        navDepartments.setForeground(new java.awt.Color(51, 255, 255));
        navDepartments.setText("Departments");
        navDepartments.setBorder(null);
        navDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navDepartmentsActionPerformed(evt);
            }
        });

        navAnalysis.setBackground(new java.awt.Color(51, 51, 51));
        navAnalysis.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        navAnalysis.setForeground(new java.awt.Color(51, 255, 255));
        navAnalysis.setText("Analysis");
        navAnalysis.setBorder(null);
        navAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navAnalysisActionPerformed(evt);
            }
        });

        navLogout.setBackground(new java.awt.Color(51, 51, 51));
        navLogout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        navLogout.setForeground(new java.awt.Color(0, 255, 255));
        navLogout.setText("Logout");
        navLogout.setBorder(null);
        navLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navLogoutActionPerformed(evt);
            }
        });

        ContentPanel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome (username)");

        javax.swing.GroupLayout ContentPanelLayout = new javax.swing.GroupLayout(ContentPanel);
        ContentPanel.setLayout(ContentPanelLayout);
        ContentPanelLayout.setHorizontalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentPanelLayout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );
        ContentPanelLayout.setVerticalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(navPatient)
                .addGap(60, 60, 60)
                .addComponent(navDoctors)
                .addGap(68, 68, 68)
                .addComponent(navDepartments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(navAnalysis)
                .addGap(93, 93, 93)
                .addComponent(navLogout)
                .addGap(85, 85, 85))
            .addGroup(navbarLayout.createSequentialGroup()
                .addComponent(ContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(navPatient)
                    .addComponent(navDoctors)
                    .addComponent(navDepartments)
                    .addComponent(navAnalysis)
                    .addComponent(navLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(ContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navDoctorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navDoctorsActionPerformed

    private void navPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navPatientActionPerformed
       
        this.getContentPane().removeAll();
        Patients patientPanel = new Patients();   
        this.add(patientPanel);
        pack();
        
    }//GEN-LAST:event_navPatientActionPerformed

    private void navDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navDepartmentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navDepartmentsActionPerformed

    private void navAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navAnalysisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navAnalysisActionPerformed

    private void navLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostLoginHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostLoginHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostLoginHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostLoginHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostLoginHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JPanel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton navAnalysis;
    private javax.swing.JButton navDepartments;
    private javax.swing.JButton navDoctors;
    private javax.swing.JButton navLogout;
    private javax.swing.JButton navPatient;
    private javax.swing.JPanel navbar;
    // End of variables declaration//GEN-END:variables
}
