/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHUBHAM
 */
public class SearchDoctorFrame extends javax.swing.JFrame {

    /**
     * Creates new form SearchDoctorFrame
     */
    public SearchDoctorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchDoctorBackground = new javax.swing.JPanel();
        SearchDoctorTitle = new javax.swing.JLabel();
        SearchDoctorTitle1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BackButton = new javax.swing.JButton();
        DoctorNameSearchField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SearchDoctorBackground.setBackground(new java.awt.Color(0, 0, 0));

        SearchDoctorTitle.setBackground(new java.awt.Color(0, 0, 0));
        SearchDoctorTitle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SearchDoctorTitle.setForeground(new java.awt.Color(0, 255, 255));
        SearchDoctorTitle.setText("Enter the Name of the Doctor : ");

        SearchDoctorTitle1.setBackground(new java.awt.Color(0, 0, 0));
        SearchDoctorTitle1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SearchDoctorTitle1.setForeground(new java.awt.Color(0, 255, 255));
        SearchDoctorTitle1.setText("Search Doctor");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Result :");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Doctor Id", "Name", "Age", "Gender", "Specialization", "Experience", "Phone No"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BackButton.setBackground(new java.awt.Color(102, 102, 102));
        BackButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BackButton.setForeground(new java.awt.Color(0, 255, 255));
        BackButton.setText("Back");
        BackButton.setBorder(null);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        DoctorNameSearchField.setBackground(new java.awt.Color(0, 0, 0));
        DoctorNameSearchField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DoctorNameSearchField.setForeground(new java.awt.Color(0, 255, 255));
        DoctorNameSearchField.setBorder(null);

        javax.swing.GroupLayout SearchDoctorBackgroundLayout = new javax.swing.GroupLayout(SearchDoctorBackground);
        SearchDoctorBackground.setLayout(SearchDoctorBackgroundLayout);
        SearchDoctorBackgroundLayout.setHorizontalGroup(
            SearchDoctorBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchDoctorBackgroundLayout.createSequentialGroup()
                .addGroup(SearchDoctorBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchDoctorBackgroundLayout.createSequentialGroup()
                        .addGroup(SearchDoctorBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SearchDoctorBackgroundLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(SearchDoctorBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(BackButton)
                                    .addGroup(SearchDoctorBackgroundLayout.createSequentialGroup()
                                        .addComponent(SearchDoctorTitle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DoctorNameSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(SearchDoctorBackgroundLayout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 617, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(SearchDoctorBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchDoctorBackgroundLayout.createSequentialGroup()
                    .addGap(272, 272, 272)
                    .addComponent(SearchDoctorTitle1)
                    .addContainerGap(700, Short.MAX_VALUE)))
        );
        SearchDoctorBackgroundLayout.setVerticalGroup(
            SearchDoctorBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchDoctorBackgroundLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(BackButton)
                .addGap(44, 44, 44)
                .addGroup(SearchDoctorBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchDoctorTitle)
                    .addComponent(DoctorNameSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(SearchDoctorBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchDoctorBackgroundLayout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(SearchDoctorTitle1)
                    .addContainerGap(587, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SearchDoctorBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SearchDoctorBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.setVisible(false);
        HospitalManagement hospitalManagement = new  HospitalManagement();
        hospitalManagement.setVisible(true);
        hospitalManagement.setLocationRelativeTo(null);// GUI comes in center
        hospitalManagement.setTitle("MediLife Hospital - Home");
        hospitalManagement.setSize(762,500);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchDoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchDoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchDoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchDoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchDoctorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField DoctorNameSearchField;
    private javax.swing.JPanel SearchDoctorBackground;
    private javax.swing.JLabel SearchDoctorTitle;
    private javax.swing.JLabel SearchDoctorTitle1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
